/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.test.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** A pair of strings. */
@org.apache.avro.specific.AvroGenerated
public class StringProject extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3218867388656418349L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StringProject\",\"namespace\":\"com.test.avro\",\"doc\":\"A pair of strings.\",\"fields\":[{\"name\":\"right\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StringProject> ENCODER =
      new BinaryMessageEncoder<StringProject>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StringProject> DECODER =
      new BinaryMessageDecoder<StringProject>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<StringProject> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<StringProject> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<StringProject>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this StringProject to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a StringProject from a ByteBuffer. */
  public static StringProject fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence right;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StringProject() {}

  /**
   * All-args constructor.
   * @param right The new value for right
   */
  public StringProject(java.lang.CharSequence right) {
    this.right = right;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return right;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: right = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'right' field.
   * @return The value of the 'right' field.
   */
  public java.lang.CharSequence getRight() {
    return right;
  }

  /**
   * Sets the value of the 'right' field.
   * @param value the value to set.
   */
  public void setRight(java.lang.CharSequence value) {
    this.right = value;
  }

  /**
   * Creates a new StringProject RecordBuilder.
   * @return A new StringProject RecordBuilder
   */
  public static com.test.avro.StringProject.Builder newBuilder() {
    return new com.test.avro.StringProject.Builder();
  }

  /**
   * Creates a new StringProject RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StringProject RecordBuilder
   */
  public static com.test.avro.StringProject.Builder newBuilder(com.test.avro.StringProject.Builder other) {
    return new com.test.avro.StringProject.Builder(other);
  }

  /**
   * Creates a new StringProject RecordBuilder by copying an existing StringProject instance.
   * @param other The existing instance to copy.
   * @return A new StringProject RecordBuilder
   */
  public static com.test.avro.StringProject.Builder newBuilder(com.test.avro.StringProject other) {
    return new com.test.avro.StringProject.Builder(other);
  }

  /**
   * RecordBuilder for StringProject instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StringProject>
    implements org.apache.avro.data.RecordBuilder<StringProject> {

    private java.lang.CharSequence right;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.test.avro.StringProject.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.right)) {
        this.right = data().deepCopy(fields()[0].schema(), other.right);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing StringProject instance
     * @param other The existing instance to copy.
     */
    private Builder(com.test.avro.StringProject other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.right)) {
        this.right = data().deepCopy(fields()[0].schema(), other.right);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'right' field.
      * @return The value.
      */
    public java.lang.CharSequence getRight() {
      return right;
    }

    /**
      * Sets the value of the 'right' field.
      * @param value The value of 'right'.
      * @return This builder.
      */
    public com.test.avro.StringProject.Builder setRight(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.right = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'right' field has been set.
      * @return True if the 'right' field has been set, false otherwise.
      */
    public boolean hasRight() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'right' field.
      * @return This builder.
      */
    public com.test.avro.StringProject.Builder clearRight() {
      right = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StringProject build() {
      try {
        StringProject record = new StringProject();
        record.right = fieldSetFlags()[0] ? this.right : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StringProject>
    WRITER$ = (org.apache.avro.io.DatumWriter<StringProject>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StringProject>
    READER$ = (org.apache.avro.io.DatumReader<StringProject>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
